### ISSUE TITLE
Call not getting connected giving 408 Request Time out

### ISSUE THREAD

**Issue by nitinpo-Kore** [jambonz/sbc-inbound#115]
[sip server 500 tst call issue.zip](https://github.com/jambonz/sbc-inbound/files/12515336/sip.server.500.tst.call.issue.zip)
 @davehorton We are placing 500 concurrent call and suddenly for one of the sip server call stopped connecting giving 408 Request Time out for approx 16 minutes attached is the drachtio log .....

**Comment by davehorton** [comment]
There is almost nothing in that log file.  What did you expect me to do with it?
