### ISSUE TITLE
Number application lookup fails when multiple carriers with same gateways are present

### ISSUE THREAD

**Issue by javibookline** [jambonz/sbc-inbound#134]
If there are several carriers with the same gateways used by an accounts, sbc-inbound only considers the first matching one to lookup an application to bind to an incoming request.

If the called DID is bound to a carrier which is not the first result of the SQL query, the application lookup fails.

This only happens for incoming INIVITES to non-dot-decimal URIs - handling of dot-decimal URIs does not have this issue.

[See this part of the code](https://github.com/jambonz/sbc-inbound/blob/03d3a9695d0a0a9b8a462e2b5bf39821e187c302/lib/db-utils.js#L176)

**Comment by davehorton** [comment]
This is strange, because I have many customers using the same carrier (for instance, twilio) over many different service providers and routing based on DID and it works fine.  I will need to look into why your scenario is different

**Comment by javibookline** [comment]
I can think of two possible reasons:

1. It could be because this case only applies to INVITEs to non-dot-decimal URIs - dot-decimal URIs do not have this issue as they are handled properly in another section of the code (actually the proposed solution is very much inspired by how this latter case is handled)
2. It could be because we have "a single owner for everything" in our jambonz system, be it a single SP with carriers used by all accounts (I am not 100% familiar with the hierarchy of SP/Accounts and the implications on how resources are handled though)
