### ISSUE TITLE
Bug: TLS padding for rtp media for srtp needed 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/sbc-inbound#159]
rtpengine is sending 

inline:PviLGhOfPiWiJUO84A01z2mzWziP4p/E6kUVYFzN9HoqgnXGm63WX6jyhJk

is 59 characters it should be 60 characters 
https://datatracker.ietf.org/doc/html/rfc3548#section-3

**Comment by davehorton** [comment]
per rtpengine docs:
```
RFC 4568 (section 6.1) is somewhat ambiguous regarding the base64 encoding format of a=crypto 
parameters added to an SDP body. The default interpretation is that trailing = characters used 
for padding should be omitted. With this flag set, these padding characters will be left in place.
```

We could add an env var to let you override the rtpengine defaults, but you should be advised you may then have other clients complaining about the opposite

**Comment by vdharashive** [comment]
Can we have this setting at carrier for each gateway ?

**Comment by xquanluu** [comment]
Created 2 new PRs for allow pad crypto on sip gateway level and both inbound and outbound shoud use same pad_crypto flag

**Comment by vdharashive** [comment]
@xquanluu @davehorton this can be merged i have tested
