### ISSUE TITLE
Clients and dialogs not released properly

### ISSUE THREAD

**Issue by bleki-teltech** [jambonz/sbc-inbound#27]
We have deployed Jambonz on Google kubernetes, during our performance tests (we are using sipp scripts) we noticed two issues;

1. Clients (connections to sbc-inbound and sbc-outbound) are not being released properly, number of connected clients is constantly rising specialy in case our app doesn't return 200 - one of our apps intentionaly releases call with 480 response, this log entry from jambonz-sbc-sip;

_drachtio 2022-03-17 12:11:23.597758 ClientController::leave - Removed client, count of connected clients is now: **33856**_

- this leads to incresed memory consumption and finaly to outage, I believe that critical number of clients is approx 34000;
    
_drachtio 2022-03-17 12:31:20.222053 Client::connect_handler tcp - unable to connect to sbc-inbound:4000_

- manual restart of sbc-inbound and sbc-outbound solves the problem

2. We have noticed that there is a large number of tracked dialogs, at this point we don't think it has big impact on jambonz performance but still we would like to understand why such large number of dialogs is tracked, e.g.

_drachtio 2022-03-17 12:11:24.325360 ClientController::removeDialog - after removing dialogs count is now: **84762**_

**Comment by davehorton** [comment]
Thanks for this great work.  Can you share your sipp scripts with me, so I can recreate? Feel free to post a link here to a gist, or email them separately to me at daveh@jambonz.org

When running in K8S the sbc-inbound app (and others) use [outbound connections](https://drachtio.org/docs/developer-guide#advanced-topics) from drachtio server rather than inbound, so they need to be released at the end of every call.  Apparently I am missing some cases.  Typically, when a call hangs up the connection [should be released here](https://github.com/jambonz/sbc-inbound/blob/e0e5c7549633ca176d3dc7ead7a64f22a98b1d6d/lib/call-session.js#L277).  That must not be happening in some cases.

Once I get your sipp scripts, what I am going to do (and you can do if you want to help in the investigation) is to place a single call through, and make sure by watching the drachtio server logs that the client connection is removed when it ends.  Then, I think it is a matter of doing more calls and finding out if there are specific call scenarios that trigger the "connection leak".

Are you on my slack channel?  If not, I would love it if you would join (got to [joinslack.jambonz.org](https://joinslack.jambonz.org)).

Thanks for this great bug report.

**Comment by bleki-teltech** [comment]
I have emailed scripts to Dave.

**Comment by davehorton** [comment]
OK I have made some fixes, can you retest?  Please update the values.yml in your helm chart as follows:

```
# sbc-inbound configuration
sbcInbound: 
  image: jambonz/sbc-inbound:latest
  imagePullPolicy: Always
  drachtioPort: "4000"
```
and
```
drachtio: 
  image: drachtio/drachtio-server:latest
```
I made fixes to each of these, and it seems to resolve the issue for me when running your uac_drop.xml script.

**Comment by davehorton** [comment]
also update to jambonz/sbc-outbound:latest, I made a fix there also.

**Comment by davehorton** [comment]
Have you retested with the changes as requested?

**Comment by bleki-teltech** [comment]
Here is a list of pods sorted by memory usage, this was taken when there was no load on the system.

![Screenshot 2022-03-22 at 09 26 39](https://user-images.githubusercontent.com/76775783/159438739-60350a9a-ed87-4244-9f45-f5c2c8a7e871.png)

**Comment by davehorton** [comment]
thanks, can you give me the command that generates that list?

Also can you tell me which of your sipp scripts you were running, and the command line options supplied

**Comment by bleki-teltech** [comment]
Command;
kubectl top pods --all-namespaces --containers=true | sort --key 5 -b | awk 'NR<1{print $0;next}{print $0| "sort --key 5 --numeric -b --reverse"}'

We are trying to simulate traffic which we expect in production, therefore I'm using 4 sipp scripts in parallel and we have configured 4 applications jambonz which are receiving instructions from 4 http services. I have already provided two of our simple scripts, other two relay on our systems and can be used only by us.

Example of the command;
sipp -p 5065 -r 9 -rp 60000 -l 1000 xxx.xxx.xxx.xxx -trace_msg -trace_err -sf uac.xml

**Comment by davehorton** [comment]
By any chance are you able to connect a node inspector to the sbc-inbound app (since that seems to be a high runner) during the testing and get memory heaps?  This could be quite useful

https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by bleki-teltech** [comment]
Heap snapshot provided via email.

**Comment by davehorton** [comment]
lets try to narrow down which of the 4 scripts seems to trigger the memory growth in sbc-inbound.  I'm going to start with your uac_connect.xml, which is a simple inbound call that connects, waits for a bit, then sends a BYE to jambonz..

**Comment by davehorton** [comment]
Can you re-run your tests with `jambonz/sbc-inbound:latest`?

I believe I tracked down and fixed the issues that I saw in my testing, would like a status from your testing.  
note: I need to make similar fixes to sbc-outbound but have not done so yet.  I'd like first to verify all issues are solved in sbc-inbound

**Comment by bleki-teltech** [comment]
Today I rerun tests with latest sbc-inbound image.
I'm afraid I don't have good new - memory consumption was increasing like before.
![Screenshot 2022-03-28 at 20 36 26](https://user-images.githubusercontent.com/76775783/160464494-9c506d52-fbcd-417d-b6af-ec099e52a7bc.png)

I run tests in 2 phases, first I run all of our load scripts and in second phase I run only the script I sent you (uac_connect.xml), in both phases memory consumption was increasing. Also, when I stopped scripts memory was not released.

**Comment by davehorton** [comment]
hmm, interesting.  different results for me.  I ran uac_connect.xml and did not see memory growth in sbc-inbound

**Comment by davehorton** [comment]
[Here is the script](https://gist.github.com/davehorton/18457fc04877054fea376b18b680fb02) I ran, using these commands:

```bash
 sipp -sf uac_connect.xml -m 2000 -l 30 -r 3 -s 503 34.70.193.255
```

Can you verify when running this script alone you see the kind of memory growth shown above?

**Comment by davehorton** [comment]
also lets make sure we are running the same code.  shell into the container and verify lib/call-session.js line 280 has this comment
```js
        /* de-link the 2 Dialogs for GC */
        dlg.removeAllListeners();
        other.removeAllListeners();
        dlg.other = null;
        other.other = null;
```

**Comment by bleki-teltech** [comment]
It seems we are not running the same code.
Today I did helm upgrade from 0.7.4. to latest, also I can see in deployment yaml that latest image is used;
image: jambonz/sbc-inbound:latest

Need to finish for today, I will check deployment tomorrow. Perhaps you could check the image?

**Comment by bleki-teltech** [comment]
I have recreated the pod and now it seems correct version was pulled. Strange.

```
}
        /* de-link the 2 Dialogs for GC */
        dlg.removeAllListeners();
        other.removeAllListeners();
        dlg.other = null;
        other.other = null;

        this.logger.info(`call ended with normal termination, there are ${this.activeCallIds.size} active`);
```

I will rerun tests tomorrow.

**Comment by davehorton** [comment]
ok thanks

**Comment by bleki-teltech** [comment]
It's looking ok now;

![Screenshot 2022-03-29 at 11 44 46](https://user-images.githubusercontent.com/76775783/160585012-180ba978-4cad-4185-b5a2-35c00ac9e2b6.png)

Please do the same correction for sbc-outbound.

Another topic, it seems that there is also a problem with memory growth on Postgres pod;

![Screenshot 2022-03-29 at 12 04 39](https://user-images.githubusercontent.com/76775783/160588242-3b803370-f5f9-4382-8ba8-e3e8852940e6.png)

What exactly is kept there? As you can see memory is not released there as well and currently 2.8 Gb is used when system is idle;

<img width="1324" alt="Screenshot 2022-03-29 at 12 11 54" src="https://user-images.githubusercontent.com/76775783/160589002-38fc2013-1d3f-417f-bac9-6de374e728f9.png">

**Comment by davehorton** [comment]
I have made the same change for sbc-outbound:latest so you can try that now.  Postgres has only postgres.  Homer writes sip traces to postgres, in tables that rotate every x days.  Not sure why it is taking so much memory

**Comment by davehorton** [comment]
btw, what console are you using in the screen shots above?

**Comment by bleki-teltech** [comment]
sbc-outbound is not behaving properly, memory is not released;
<img width="761" alt="Screenshot 2022-03-29 at 21 16 22" src="https://user-images.githubusercontent.com/76775783/160690110-65f91f85-072d-423e-a238-ccbff9a48457.png">


sbc-inbound is ok;

<img width="756" alt="Screenshot 2022-03-29 at 21 17 01" src="https://user-images.githubusercontent.com/76775783/160690223-7ffcfa64-94d4-4714-9540-62e19f3abd75.png">



Just to make sure that I have correct software on sbc-outbound, this part of the code starts at line 452 in lib/call-session.js, 
   
        /* de-link the 2 Dialogs for GC */
        dlg.removeAllListeners();
        other.removeAllListeners();
        dlg.other = null;
        other.other = null;

**Comment by davehorton** [comment]
ok, thanks will investigate..

**Comment by davehorton** [comment]
I've checked in a fix for sbc-outbound which I believe may fix this leak.  Could you retest with the latest tag when you get a chance?

**Comment by bleki-teltech** [comment]
I have re-tested today latest fix and can confirm that memory problems on sbc-inbound and sbc-outbound are solved!
Thanks!
I guess you will produce new release? 0.7.5?

**Comment by davehorton** [comment]
Yes, I have put a tag v0.7.5-rc1 on the repos and built docker images with tag 0.7.5-rc1.
