### ISSUE TITLE
Sip Refer Does not resolve to uri address

### ISSUE THREAD

**Issue by vdharashive** [jambonz/sbc-inbound#60]
"type": "command",
  "call_sid": "f2f109b3-a796-45af-9016-dd6ceadb7132",
  "command": "redirect",
  "queueCommand": true,
  "data": [
    {
      "verb": "sip:refer",
      "actionHook": "/transferStatus",
      "eventHook": "/events",
      "referTo": "sip:12345@X.Y.Z.A:5060",
      }
]

sip:refer does not originate call to refer uri but it replaces the Ip address of URI with source ip address

**Comment by davehorton** [comment]
I think it replaces the ip address in the referTo with the ip address/hostname of the outbound gateway for the carrier, correct?  Currently, this is because twilio actually requires that when transferring a call via REFER to a PSTN number, but I agree we need to limit this case
