### ISSUE TITLE
database cache not updating after long period

### ISSUE THREAD

**Issue by Megamuch** [jambonz/sbc-inbound#83]
we've noticed that the database cache which contains the configuration of which DID goes to what application does not get updated any longer after long periods of inactivity. 

Example: 
we changed a DID from application A to application B through the web interface today. verified the DB was indeed updated with the new values.  JAMBONES_MYSQL_REFRESH_TTL: 60

After waiting for more than 5 minutes we expect the application cache to be updated. Nothing changes. Untill we do a pm2 restart all on the sbc and then the new information is cached again. 

I don't see any logs or errors in pm2 related to the caching so I'm not sure where to look in the code base.

**Comment by xquanluu** [comment]
Checking the issue.

**Comment by xquanluu** [comment]
Hi @Megamuch 

By using integration test, v0.8.1, I cannot reproduce the issue, After 60 Seconds, The cache is working fine here. Here are testcase I have tested:

1/ Test Case 1
- Update phone Number with new app Id, 
- Send INVITE to DID, 
- After 35 seconds, 
- Send INVITE to DID (old app id is used for this INVITE)
- Update DID with new app ID
- Send INVITE to DID (old app id is used for this INVITE)
- After 35 seconds
- Send INVITE to DID (new app ID is used)

Can you tell me which jambonz version you are using? as my testcase is running on latest code.

**Comment by Megamuch** [comment]
Hi @xquanluu we are running the 7.9-11 version still. Upgrade to 0.8.1 is planned but not soon (ie, within weeks).

We have found the issue to only occur after longer periods of inactivity. if we restart the sbc, it will remain working for a long time. Only after days we found it to stop updating. 
I doubt an integration test will show you the same result. 
Is there a specific area where I could add a debug message to check what is going on?

**Comment by xquanluu** [comment]
Thanks @Megamuch 
the source code of caching db is from https://github.com/jambonz/db-helpers/blob/main/lib/cache-manager.js#L18.

You can see 2 debug at line 18 and 38. Can you add debug level to pm2 on sbc-inbound and check if we can see some inside there of the updater still run after 1 days?

**Comment by Megamuch** [comment]
I haven't noticed this behavior in the latest 0.8.4 versions so I'm closing this one.
