### ISSUE TITLE
Inbound calls answered on MacOS ReachUC drop calls at exactly 1 min

### ISSUE THREAD

**Issue by timmeade** [jambonz/sbc-inbound#84]
Tested on 3 macs running 2 versions of OS including latest

Skyswitch (coredial) uses reach uc as the mobile app to their ucass. 

Works fine with ios/android.  Works fine with hard wired desk phones. 

Tested with macs both wifi and hard wired.  All fail on inbound calls.  All work on outbound.

When inbound to mac os drops exactly at 1 min every time.  Tested on 3 inbound numbers with 3 different carriers into jambonz.

ReachUC claims on reinvite switching to opus codec.   

Attached pcap.

[1-min-call.zip](https://github.com/jambonz/sbc-inbound/files/10959728/1-min-call.zip)

**Comment by davehorton** [comment]
can you provide the SIP call-id of the call that failed in this way?  There are multiple calls in this pcap

**Comment by timmeade** [comment]
Should Call-ID: f89ab4d0-55b5-45aa-a200-fd6cebbbedf1

**Comment by timmeade** [comment]
proto:UDP 2023-03-13T16:56:14.284509Z  10.10.163.74:5060 ---> 52.5.55.85:5060

INVITE sip:+12396287070@34.233.108.66:5070 SIP/2.0
Via: SIP/2.0/UDP 3.128.22.58;rport;branch=z9hG4bKeZ4tU0a78yZNF
Route: <sip:52.5.55.85:5060;lr=on>
Max-Forwards: 70
From: <sip:18885246151@3.128.22.58>;tag=4S9j0XetNvcyr
To: <sip:12396287070@34.233.108.66;isup-oli=62>;tag=avUZtvmcQt3jj
Call-ID: f89ab4d0-55b5-45aa-a200-fd6cebbbedf1
CSeq: 64809494 INVITE
Contact: <sip:3.128.22.58:5060>
Content-Type: application/sdp
Content-Length: 594

v=0
o=NetSapiens_Nms 1678726570 1678726574220 IN IP4 3.128.22.58
s=legmdld
c=IN IP4 3.128.22.58
t=0 0
m=audio 41046 RTP/AVP 102 101
a=ssrc:1644937864 cname:xqxzBI4L4ahvEG7S
a=ssrc:1644937864 msid:44307141-fec2-4eb5-a1ea-b904d867dbba 34ed2c54-cf63-405f-8456-e6fc090b48e4
a=ssrc:1644937864 mslabel:44307141-fec2-4eb5-a1ea-b904d867dbba
a=ssrc:1644937864 label:34ed2c54-cf63-405f-8456-e6fc090b48e4
a=rtpmap:102 opus/48000/2
a=fmtp:102 maxplaybackrate=16000;maxaveragebitrate=30000;useinbandfec=1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:41047
a=ptime:20

proto:UDP 2023-03-13T16:56:14.295908Z  52.5.55.85:5060 ---> 10.10.163.74:5060

SIP/2.0 100 Giving a try
Via: SIP/2.0/UDP 3.128.22.58;rport=5060;branch=z9hG4bKeZ4tU0a78yZNF
From: <sip:18885246151@3.128.22.58>;tag=4S9j0XetNvcyr
To: <sip:12396287070@34.233.108.66;isup-oli=62>;tag=avUZtvmcQt3jj
Call-ID: f89ab4d0-55b5-45aa-a200-fd6cebbbedf1
CSeq: 64809494 INVITE
Server: TSG-GLOBAL-COBRA
Content-Length: 0


proto:UDP 2023-03-13T16:56:14.553864Z  52.5.55.85:5060 ---> 10.10.163.74:5060

SIP/2.0 488 Not Acceptable Here
Via: SIP/2.0/UDP 3.128.22.58;received=3.128.22.58;rport=5060;branch=z9hG4bKeZ4tU0a78yZNF
From: <sip:18885246151@3.128.22.58>;tag=4S9j0XetNvcyr
To: <sip:12396287070@34.233.108.66;isup-oli=62>;tag=avUZtvmcQt3jj
Call-ID: f89ab4d0-55b5-45aa-a200-fd6cebbbedf1
CSeq: 64809494 INVITE
User-Agent: TSG-GLOBAL-COBRA
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Content-Length: 0

**Comment by davehorton** [comment]
The problem is that after establishing a call between an A party and a B party using PCMU, the B party immediately reinvites with opus.  The A party does not support opus so the call is dropped.

It is a bit strange for the B party (ReachUC) to be offered opus in the initial INVITE, decline it, and then after the call is immediately established with PCMU to reINVITE requesting only opus.  I would raise a ticket and get an explanation from them on why they are doing this.

This is the signaling on that B leg
```
** We send INVITE to ReachUC offering PCMU, PCMA, and OPUS

INVITE sip:8885246151@70.42.44.171 SIP/2.0
Via: SIP/2.0/UDP 3.128.22.58;rport;branch=z9hG4bK6ptmD83a0QD0j
Max-Forwards: 70
From: <sip:12396287070@3.128.22.58:5060>;tag=522B2rZXj52gm
To: <sip:8885246151@3.128.22.58:5060>
Call-ID: cc0e4deb-3c62-123c-2ab0-0ad5cd4a2246
CSeq: 64809493 INVITE
Contact: <sip:12396287070@3.128.22.58:5060>
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, NOTIFY, UPDATE, PRACK
Content-Type: application/sdp
Content-Length: 491
X-Account-Sid: 9351f46a-678c-43f5-b8a6-d4eb58d131af
X-CID: f89ab4d0-55b5-45aa-a200-fd6cebbbedf1
X-Call-Sid: 1e69ea18-3972-4a6c-b66b-e00695474ebe

v=0
o=FreeSWITCH 1678697700 1678697701 IN IP4 3.128.22.58
s=FreeSWITCH
c=IN IP4 3.128.22.58
t=0 0
m=audio 41054 RTP/AVP 0 8 102 9 101 103
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:103 telephone-event/48000
a=fmtp:103 0-16
a=sendrecv
a=rtcp:41055
a=ptime:20

SIP/2.0 100 trying -- your call is important to us
Via: SIP/2.0/UDP 3.128.22.58;rport=5060;branch=z9hG4bK6ptmD83a0QD0j;received=3.128.22.58
From: <sip:12396287070@3.128.22.58:5060>;tag=522B2rZXj52gm
To: <sip:8885246151@3.128.22.58:5060>
Call-ID: cc0e4deb-3c62-123c-2ab0-0ad5cd4a2246
CSeq: 64809493 INVITE
Server: kamailio (5.6.1 (x86_64/linux))
Content-Length: 0

*** They respond removing OPUS, and indicating either PCMU or PCMA is acceptable

SIP/2.0 200 OK
Record-Route: <sip:70.42.44.171;lr;ftag=522B2rZXj52gm;did=f46.be53>
Via: SIP/2.0/UDP 3.128.22.58;received=3.128.22.58;rport=5060;branch=z9hG4bK6ptmD83a0QD0j
To: <sip:8885246151@3.128.22.58:5060>;tag=9FkZ1HWji6R6Y9IlB76084
From: <sip:12396287070@3.128.22.58:5060>;tag=522B2rZXj52gm
Call-ID: cc0e4deb-3c62-123c-2ab0-0ad5cd4a2246
CSeq: 64809493 INVITE
Contact: <sip:system@207.254.80.15:5060;transport=udp>
Server: NetSapiens SiPBx v43-2-0x83
Content-Type: application/sdp
Content-Length: 268

v=0
o=NetSapiens_Nms 1678726570 1678726570073 IN IP4 207.254.80.15
s=SIP Media Description
c=IN IP4 207.254.80.15
t=0 0
m=audio 34332 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000/1
a=rtpmap:8 PCMA/8000/1
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv

*** The call is now connected using PCMU

*** One second later, they re-INVITE requesting OPUS -- which they previously dropped from the call

INVITE sip:12396287070@3.128.22.58:5060 SIP/2.0
Via: SIP/2.0/UDP 70.42.44.171;branch=z9hG4bK2257.7a15d0d53ae95691eaa3865dd0699a05.0
Via: SIP/2.0/UDP 207.254.80.15:5060;branch=z9hG4bKRhxsc4CzbrYow3Y1B76964
From: <sip:8885246151@3.128.22.58:5060>;tag=9FkZ1HWji6R6Y9IlB76084
To: <sip:12396287070@3.128.22.58:5060>;tag=522B2rZXj52gm
Call-ID: cc0e4deb-3c62-123c-2ab0-0ad5cd4a2246
CSeq: 101 INVITE
Max-Forwards: 60
Contact: <sip:system@207.254.80.15:5060;transport=udp>
Server: NetSapiens SiPBx v43-2-0x83
Content-Type: application/sdp
Content-Length: 584
P-hint: rr-enforced

v=0
o=NetSapiens_Nms 1678726570 1678726574220 IN IP4 207.254.80.15
s=legmdld
c=IN IP4 207.254.80.15
t=0 0
m=audio 28098 RTP/AVP 102 101
a=rtpmap:101 telephone-event/8000
a=rtpmap:102 opus/48000/2
a=fmtp:101 0-15
a=fmtp:102 maxplaybackrate=16000;maxaveragebitrate=30000;useinbandfec=1
a=ptime:20
a=sendrecv
a=ssrc:1644937864 cname:xqxzBI4L4ahvEG7S
a=ssrc:1644937864 msid:44307141-fec2-4eb5-a1ea-b904d867dbba 34ed2c54-cf63-405f-8456-e6fc090b48e4
a=ssrc:1644937864 mslabel:44307141-fec2-4eb5-a1ea-b904d867dbba
a=ssrc:1644937864 label:34ed2c54-cf63-405f-8456-e6fc090b48e4
```

**Comment by timmeade** [comment]
From the REACH UC Side (BS in my mind) 

Note we talk to the queue operator for the 1 minute on the reach uc which works just fine:

_These are calls into a call queue. The call queue is not going to use OPUS to
set up the initial call between the caller and the call queue (Its going to
use g711). The call queue dispatches the call to the ReachUC user who then
negotiates OPUS (because ReachUC uses the OPUS codec). Do you have an isssue
if you call directly to the ReachUC device (bypassing the call queue)?_

**Comment by timmeade** [comment]
That is what they are claiming.  It also does not give a reason why everything works fine on IOS but not on MACs.

**Comment by timmeade** [comment]
That worked fine. Not going through call center queue to Mac ReachUC worked fine.   They are now claiming the "Working" examples were not 1 min.   I am regenerating those now

**Comment by davehorton** [comment]
How would I go about recreating this on my own server?

**Comment by timmeade** [comment]
Not sure.   Might be easier to give you access to mine if that would work.

**Comment by timmeade** [comment]
From them:

The issue here is when the DID routes to the call queue, we negotiate the
codec g711. Once the call queue dispatches the call to the ReachUC user,
ReachUC negotiates OPUS and the originating carrier is not sending us a 200OK
response, instead they respond to you with a 488 and then our switch times out
at 1 minute because we don't receive a response. Your option here is to either
route calls directly to the ReachUC user, OR have your originating carrier
respond to our reINVITE (containing the OPUS codec) with a 200OK.

**Comment by davehorton** [comment]
The fix here would be fairly complicated and would need a lot of testing which could not be done on your production system
